# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    loaders:
        default:
            filesystem:
                locator:    filesystem
                data_root:
                    -   '%kernel.project_dir%/public'
    resolvers:
        default:
            web_path:   ~
    cache: default
    cache_base_path:    ''
    data_loader:    default
    default_image:  null
    filter_sets:
        admin_produit:
            quality:    100
            jpeg_quality:   100
            filters:
                thumbnail:  {size:  [90, 90], mode: inset, allow_upscale:   true }
                background: {size:  [90, 90], position: center }
        choix_produit:
            quality:    100
            jpeg_quality:   100
            filters:
                thumbnail:  {size:  [350, 240], mode: inset, allow_upscale: true }
                background: {size:  [354, 244], position: center }