twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        entreprise_nom: Plastic R Cube
        entreprise_email: contact@plasticrcube.fr
        entreprise_tel: +33 6 62 05 76 66
        entreprise_adresse: 679 Avenue de la République
        entreprise_cp: 59800
        entreprise_ville: Lille
        entreprise_pays: France
        entreprise_status: SARL au capital de 3000 €
        entreprise_code_naf: 3319Z
        entreprise_siret: 887 741 742 R.C.S. Lille Métropole
        entreprise_tva: FR28 887 741 742
        entreprise_site: www.plasticrcube.fr
        entreprise_banque: 30027
        entreprise_code_banque: 17011
        entreprise_compte: 00021173701
        entreprise_iban: FR76 3002 7170 1100 0211 7370 115
        entreprise_bic: CMCIFRPP


